---
---
---

# 

```{r}
#Librerias
library(limma)
library(readxl)
library(ggplot2)
library(Biobase)
library(dplyr)
library(tidyr)
library(gridExtra)
library(openxlsx)
```

## Lectura y Ajuste de los datos

```{r}
df=read_xlsx("E:/Proyectos/33.LimmaFirmasEspectralesWeights/Modeling_SpectralSignatures/Spectral_signatures.xlsx")
df$WATER=ifelse(df$WATER=='CW',1,0)
df
```

## Funciones

```{r}
#Graficas comparativas entre dos pvalores 
plot_pvalues <- function(wavelengths, pval_0, pval_1, y_label = "-log p value", 
                         color_0 = "black", color_1 = "red", 
                         label_0 = "Category 1", label_1 = "Category 2",
                         plot_title = "P-Value Plot") {
  # Crear un data frame con los valores de entrada
  df_graph <- data.frame(x = wavelengths, pval_0, pval_1)
  
  ggplot(df_graph, aes(x = x)) +
    # Graficar los puntos de los valores p transformados
    geom_point(aes(y = -log(pval_0, base = 10), color = color_0), size = 1, shape = 16) +
    geom_point(aes(y = -log(pval_1, base = 10), color = color_1), size = 1, shape = 16) +
    
    # Agregar líneas horizontales para umbrales de significancia
    geom_hline(yintercept = -log(0.05, base = 10), color = "darkblue", linetype = 'dashed') +
    geom_hline(yintercept = -log(0.03, base = 10), color = "red", linetype = 'dashed') +
    geom_hline(yintercept = -log(0.01, base = 10), color = "black", linetype = 'dashed') +
    
    # Personalizar colores y etiquetas
    scale_color_manual(values = c(color_0, color_1), labels = c(label_0, label_1)) +
    
    # Ajustar el estilo del gráfico
    theme_minimal() +
    xlab('Wavelength (nm)') +
    ylab(y_label) +
    labs(color = "Method", title = plot_title) +
    theme(plot.title = element_text(hjust = 0.5))
}
```

```{r}
#Metodologia de p valor con ajuste clasico
extract_pvalues <- function(df, model_formula, 
                            start_col = 1, end_col = ncol(df), 
                            apply_correction = TRUE, correction_method = "fdr") {
  
  # Obtener nombres de variables del modelo
  vars <- all.vars(model_formula)
  
  # Listas para almacenar los p-valores
  pvalues <- list()
  
  for (i in start_col:end_col) {
    # Construir el modelo dinámicamente
    formula_str <- paste("df[[i]] ~", paste(vars, collapse = " * "))
    mod <- summary(lm(as.formula(formula_str), data = df))
    
    # Extraer p-valores
    for (var in vars) {
      if (var %in% rownames(mod$coefficients)) {
        pvalues[[var]] <- c(pvalues[[var]], mod$coefficients[var, 'Pr(>|t|)'])
      } else {
        pvalues[[var]] <- c(pvalues[[var]], NA)  # Si la variable no está, poner NA
      }
    }
    
    # Interacción (si aplica)
    interaction_term <- paste(vars, collapse = ":")
    if (interaction_term %in% rownames(mod$coefficients)) {
      pvalues[[interaction_term]] <- c(pvalues[[interaction_term]], mod$coefficients[interaction_term, 'Pr(>|t|)'])
    } else {
      pvalues[[interaction_term]] <- c(pvalues[[interaction_term]], NA)
    }
  }
  
  # Aplicar corrección si es necesario
  if (apply_correction) {
    for (key in names(pvalues)) {
      pvalues[[key]] <- p.adjust(pvalues[[key]], method = correction_method)
    }
  }
  
  return(pvalues)
}
```

```{r}
#metodologia de pvalor con limma
extract_pvalues_limma <- function(df, model_formula, 
                                  start_col = 3, end_col = ncol(df), 
                                  weights = NULL,
                                  correction_method = "fdr") {
  
  # Extraer nombres de variables del modelo
  vars <- all.vars(model_formula)
  
  # Transponer la matriz de datos para usar en limma
  expression_data <- as.data.frame(t(df[, start_col:end_col]))
  
  # Crear la matriz de diseño
  design <- model.matrix(as.formula(paste("~", paste(vars, collapse = " * "))), data = df)
  
  # Ajustar el modelo con lmFit y eBayes, usando pesos si se proporcionan
  if (!is.null(weights)) {
    mod <- lmFit(expression_data, design, weights = weights)
  } else {
    mod <- lmFit(expression_data, design)
  }
    fit <- eBayes(mod)
  
  # Extraer p-valores
  pvalues <- list()
  
  for (i in 2:ncol(design)) {  # Coeficientes desde el 2 (el 1 es el intercepto)
    coef_name <- colnames(design)[i]
    
    fit_table <- topTable(fit, coef = i, adjust.method = correction_method, number = end_col)
    fit_table$index <- as.numeric(rownames(fit_table))
    fit_table <- fit_table %>% arrange(index)
    
    pvalues[[coef_name]] <- fit_table[, 5]  # Extrae la columna de p-valores
  }
  
  return(pvalues)
}
```

```{r}
#rangos de bandas con pvalores superiores al establecido
buscar_rangos_superiores <- function(pvalues, columna_x, filtros) {
  for (filtro in filtros) {
    # Mostrar la separación para el filtro actual
    print(paste("------------- Filtro:", filtro, "-------------"))
    
    # Aplicar la transformación -log10 a los valores de p-values y al filtro
    log_y <- -log10(pvalues)
    filtro_log <- -log10(filtro)
    
    # Crear una lista para almacenar los rangos
    rangos <- list()
    
    # Inicializar variables para el rango actual
    inicio_rango <- NULL
    fin_rango <- NULL
    
    # Iterar a través de los valores
    for (i in seq_along(columna_x)) {
      # Verificar si el valor de -log10(p-value) es mayor al umbral
      if (log_y[i] > filtro_log) {
        # Si es el comienzo del rango, guardar el valor de x
        if (is.null(inicio_rango)) {
          inicio_rango <- columna_x[i]
        }
        # Actualizar el valor final del rango
        fin_rango <- columna_x[i]
      } else {
        # Si se encuentra un valor menor o igual al umbral y hay un rango activo, almacenarlo
        if (!is.null(inicio_rango)) {
          rangos[[length(rangos) + 1]] <- c(inicio_rango, fin_rango)
          # Reiniciar los índices de inicio y fin del rango
          inicio_rango <- NULL
          fin_rango <- NULL
        }
      }
    }
    
    # Si hay un rango activo al final, almacenarlo
    if (!is.null(inicio_rango)) {
      rangos[[length(rangos) + 1]] <- c(inicio_rango, fin_rango)
    }
    
    # Imprimir los rangos encontrados
    for (i in seq_along(rangos)) {
      print(paste("Rango", i, rangos[[i]][1], ":", rangos[[i]][2]))
    }
  }
}


```

## Modelos lm

```{r}
#P-values for the interaction are extracted
result <- extract_pvalues(df, model_formula = ~ NITROGEN * WATER,start_col = 3)
nitro_0=result$NITROGEN
water_0=result$WATER
inter_0=result$`NITROGEN:WATER`

#Correccion
result <- extract_pvalues(df, model_formula = ~ NITROGEN * WATER,start_col = 3,apply_correction = FALSE)
nitro_1=result$NITROGEN
water_1=result$WATER
inter_1=result$`NITROGEN:WATER`

```

```{r}
title = "Comparacion datos originales y corregidos con P.adjust y frd"
wavelengths <- seq(350, 2500)
plot_pvalues(wavelengths, nitro_0, nitro_1, color_0 = "darkgreen", color_1 = "purple", label_0 = "Normal", label_1 = "Corregido",plot_title = title)
```

```{r}
print(paste("------------- pValores sin ajustar -------------"))
wavelengths <- seq(350, 2500)
filtros <- c(0.05, 0.01, 0.001)  # Lista de filtros
rangos_nitro <- buscar_rangos_superiores(nitro_0, wavelengths, filtros)

```

```{r}
print(paste("------------- pValores con ajuste fdr -------------"))
wavelengths <- seq(350, 2500)
filtros <- c(0.05, 0.01, 0.001)  # Lista de filtros
rangos_nitro <- buscar_rangos_superiores(nitro_1, wavelengths, filtros)

```

## Modelos Limma

```{r}
#limma sin pesos fdr
result <- extract_pvalues_limma(df, model_formula = ~ NITROGEN * WATER)
nitro_2=result$NITROGEN
water_2=result$WATER
inter_2=result$`NITROGEN:WATER`
# limma pesos resolucion espectral 350 a 1000 + 3 y 1000 a 2500 =6
esLong <- seq(350, 2500)
weightsEs <- ifelse(esLong > 1000, 6, 3)
result <- extract_pvalues_limma(df, model_formula = ~ NITROGEN * WATER, weights = weightsEs)
nitro_3=result$NITROGEN
water_3=result$WATER
inter_3=result$`NITROGEN:WATER`
# limma pesos resolucion espectral  350 a 1000 + 3 y 1000 a 2500 =8
esLong <- seq(350, 2500)
weightsEs <- ifelse(esLong > 1000, 8, 3)
result <- extract_pvalues_limma(df, model_formula = ~ NITROGEN * WATER, weights = weightsEs)
nitro_4=result$NITROGEN
water_4=result$WATER
inter_4=result$`NITROGEN:WATER`
# limma pesos resolucion espectral 350 a 1000 + 3 y 1000 a 2500 =10
esLong <- seq(350, 2500)
weightsEs <- ifelse(esLong > 1000, 10, 3)
result <- extract_pvalues_limma(df, model_formula = ~ NITROGEN * WATER, weights = weightsEs)
nitro_5=result$NITROGEN
water_5=result$WATER
inter_5=result$`NITROGEN:WATER`
# limma pesos 350 a 1000 + 3 y 1000 a 2500 =30
esLong <- seq(350, 2500)
weightsEs <- ifelse(esLong > 1000, 30, 3)
result <- extract_pvalues_limma(df, model_formula = ~ NITROGEN * WATER, weights = weightsEs)
nitro_6=result$NITROGEN
water_6=result$WATER
inter_6=result$`NITROGEN:WATER`

```

```{r}
title = "Comparacion limma sin pesos y con pesos resulucion 30"
wavelengths <- seq(350, 2500)
plot_pvalues(wavelengths, nitro_2, nitro_6, color_0 = "darkgreen", color_1 = "purple", label_0 = "limma", label_1 = "limma pesos",plot_title = title)
```

```{r}
print(paste("------------- pValores con limma -------------"))
wavelengths <- seq(350, 2500)
filtros <- c(0.05, 0.01, 0.001)  # Lista de filtros
rangos_nitro <- buscar_rangos_superiores(nitro_2, wavelengths, filtros)
```

```{r}
print(paste("------------- pValores con limma -------------"))
print(paste("----------- resolucion espectral 3 (350-1000) y 6 (1000-2500) -----------"))
wavelengths <- seq(350, 2500)
filtros <- c(0.05, 0.01, 0.001)  # Lista de filtros
rangos_nitro <- buscar_rangos_superiores(nitro_3, wavelengths, filtros)
```

```{r}
print(paste("------------- pValores con limma -------------"))
print(paste("----------- resolucion espectral 3 (350-1000) y 8 (1000-2500) -----------"))
wavelengths <- seq(350, 2500)
filtros <- c(0.05, 0.01, 0.001)  # Lista de filtros
rangos_nitro <- buscar_rangos_superiores(nitro_4, wavelengths, filtros)
```

```{r}
print(paste("------------- pValores con limma -------------"))
print(paste("----------- resolucion espectral 3 (350-1000) y 10 (1000-2500) -----------"))
wavelengths <- seq(350, 2500)
filtros <- c(0.05, 0.01, 0.001)  # Lista de filtros
rangos_nitro <- buscar_rangos_superiores(nitro_5, wavelengths, filtros)
```

```{r}
print(paste("------------- pValores con limma -------------"))
print(paste("----------- resolucion espectral 3 (350-1000) y 30 (1000-2500) -----------"))
wavelengths <- seq(350, 2500)
filtros <- c(0.05, 0.01, 0.001)  # Lista de filtros
rangos_nitro <- buscar_rangos_superiores(nitro_6, wavelengths, filtros)

```
